FROM public.ecr.aws/lambda/go:1
ARG AWS_ACCOUNT_ID
ARG AWS_REGION
ARG SPARTA_BINARY
ARG SPARTA_ECR_LABEL_NAME
ARG SPARTA_BUILD_ID
LABEL ${SPARTA_ECR_LABEL_NAME}=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/spartaoci:${SPARTA_BUILD_ID}
COPY ${SPARTA_BINARY} /var/task/SpartaOCI
WORKDIR /var/task
CMD [ "SpartaOCI" ]
